[workspace]
members = ["usbh", "usbh-rp2040"]
default-members = ["usbh", "usbh-rp2040"]
resolver = "2"

[workspace.package]
authors = ["Niklas Cathor"]
edition = "2021"
keywords = ["no-std", "embedded", "usb"]
license = "MIT"
homepage = "https://github.com/nilclass/usbh"
repository = "https://github.com/nilclass/usbh"
