[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

name = "usbh-rp2040"
version = "0.1.0"
description = "Experimental host-side USB stack for embedded devices: RP2040 bus implementation"

[dependencies]
usbh = { path = "../usbh" }
usb-device = { version = "0.3.2", features = ["defmt"] }

rp2040-hal = { version = "0.10.2" }
critical-section = "1.2.0"
cortex-m = "0.7"
